# Generated by Django 2.2 on 2020-05-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplyForm',
            new_name='ApplyModel',
        ),
    ]
