# Generated by Django 2.2 on 2020-05-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200503_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datemodel',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='datemodel',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
