# Generated by Django 2.2 on 2020-05-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200506_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
