# Generated by Django 2.2 on 2020-05-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_applicationmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
