# Generated by Django 2.2 on 2020-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20200507_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
