# Generated by Django 2.2 on 2020-05-15 01:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'lecture', 'verbose_name_plural': 'lectures'},
        ),
        migrations.AddField(
            model_name='lecture',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 1, 23, 19, 317452, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='lecture',
            name='download_resources',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='lecture',
            name='upload_resources',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lecture',
            name='zoom_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='lecture',
            table=None,
        ),
    ]
