# Generated by Django 2.2 on 2020-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
