# Generated by Django 2.2 on 2020-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_lecture_meeting_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='meeting_timing',
            field=models.TimeField(null=True),
        ),
    ]
