# Generated by Django 2.2 on 2020-05-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200515_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('R', 'Running'), ('C', 'Completed'), ('P', 'Not Started')], default='P', max_length=1),
        ),
    ]
