# Generated by Django 2.2 on 2020-05-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_num',
            field=models.IntegerField(default=1),
        ),
    ]
