# Generated by Django 2.2 on 2020-05-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_slack_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='download_resources',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_num',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='meeting_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='upload_resources',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='zoom_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
