# Generated by Django 2.2 on 2020-05-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20200518_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TimeField(blank=True, default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='download_resources',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
