# Generated by Django 2.2 on 2020-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20200518_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='download_resources',
            field=models.FileField(blank=True, null=True, upload_to='static/Instructor/'),
        ),
    ]
