# Generated by Django 2.2 on 2020-05-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20200518_1258'),
        ('course', '0017_auto_20200518_1255'),
    ]

    operations = [
    ]
