# Generated by Django 2.2 on 2020-05-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_merge_20200518_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='upload_resources',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='download_resources',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
