# Generated by Django 2.2 on 2020-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=500)),
                ('hear_about_us', models.CharField(max_length=100)),
            ],
        ),
    ]
