# Generated by Django 2.2 on 2020-05-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
