# Generated by Django 2.2 on 2020-05-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_applicationmodel_email_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'Selected User', 'verbose_name_plural': 'Selected Users'},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='education',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='hear_about',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='mobile_num',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
