# Generated by Django 2.2 on 2020-05-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200504_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datemodel',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relateds', to='login.CourseModel'),
        ),
    ]
