# Generated by Django 2.2 on 2020-05-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_usermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='timing_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
