# Generated by Django 2.2 on 2020-06-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_applicationmodel_timing_mail_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datemodel',
            old_name='registeration',
            new_name='registeration_limit',
        ),
        migrations.AddField(
            model_name='datemodel',
            name='closed_at',
            field=models.IntegerField(default=0),
        ),
    ]
