# Generated by Django 2.2 on 2020-05-05 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200504_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.CourseModel', to_field='name'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
