# Generated by Django 2.2 on 2020-06-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200601_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datemodel',
            old_name='registeration_limit',
            new_name='registeration',
        ),
    ]
