# Generated by Django 2.2 on 2020-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200505_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='instituteOrStartup',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='student_details',
            field=models.CharField(choices=[('ER', 'Entrepreneur'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='null', max_length=2),
        ),
    ]
