# Generated by Django 2.2 on 2020-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200601_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='certificate_grade',
            field=models.CharField(choices=[('VGD', 'Very Good'), ('GOD', 'Good'), ('SAT', 'Satisfactory'), ('EXE', 'Excellent'), ('NVA', 'Not Valid')], default='NVA', max_length=3),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='enable_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
