# Generated by Django 2.2 on 2020-06-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200607_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('certificate_grade', models.CharField(choices=[('VGD', 'Very Good'), ('GOD', 'Good'), ('SAT', 'Satisfactory'), ('EXE', 'Excellent'), ('NVA', 'Not Valid')], default='NVA', max_length=3)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
