# Generated by Django 2.2 on 2020-05-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200506_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='student_details',
            field=models.CharField(max_length=100),
        ),
    ]
