# Generated by Django 2.2 on 2020-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_certificates_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates_list',
            name='date',
        ),
        migrations.AddField(
            model_name='certificates_list',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificates_list',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
