# Generated by Django 2.2 on 2020-06-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200611_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates_list',
            name='certificate_grade',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
