# Generated by Django 2.2 on 2020-06-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200611_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='is_fail',
            field=models.BooleanField(default=False),
        ),
    ]
