# Generated by Django 2.2 on 2020-05-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20200507_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='mobile_num',
            field=models.IntegerField(),
        ),
    ]
