# Generated by Django 2.2 on 2020-05-08 09:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20200507_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='mobile_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
