# Generated by Django 2.2 on 2020-05-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20200511_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='datemodel',
            name='registeration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
